version: '2'
services:
    
    #DATABASE
    db: 
        image: postgres:9.6
        environment: 
            POSTGRES_DB: ${DBNAME}
            DBROOTUSER: ${DBROOTUSER}
            DBROOTPASSWORD: ${DBROOTPASSWORD}
            POSTGRES_USER: ${DBUSER}
            POSTGRES_PASSWORD: ${DBPASSWORD}
        volumes:
            - ${DBVOLUMEFOLDER}:/var/lib/postgresql/data
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - backend-internal

    #SOURCES BACKEND
    backend-php:
        build:
            context: ./php
            dockerfile: Dockerfile
            args:
                - TIMEZONE=Europe/Luxembourg
        volumes:
            - backend-php-data:/var/www/symfony
        restart: unless-stopped
        networks:
            - backend-internal

    #NGINX BACKEND 
    backend-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        ports: 
            - 80
        volumes:
            - backend-php-data:/var/www/symfony
        depends_on:
            - backend-php
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - default
            - backend-internal

volumes:
    backend-php-data:
    
#CONTAINERS NETWORK
networks:
  backend-internal:
  default:
    external:
      name: nginx-proxy
            
