version: '2'
services:
    
    #DATABASE
    db: 
        image: postgres:9.6
        environment: 
            - DBROOTPASSWORD=postgres24
            - DBROOTUSER=postgres
            - POSTGRES_PASSWORD=pass_myeasyrgpd
            - POSTGRES_USER=user_myeasyrgpd
            - POSTGRES_DB=db_myeasyrgpd
        volumes:
            - back-easyrgpd-postgres-data:/var/lib/postgresql/data

    #SOURCES BACKEND
    backend-php:
        build:
            context: ./php
            dockerfile: Dockerfile
            args:
                - TIMEZONE=Europe/Luxembourg
        volumes:
            - back-easyrgpd-php-data:/var/www/symfony

    #NGINX BACKEND 
    backend-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        ports: 
            - ${HOST_PORT}:80
        volumes:
            - back-easyrgpd-php-data:/var/www/symfony
        depends_on:
            - backend-php
        env_file:
            - .env

#CONTAINERS NETWORK
networks:
  default:
    external:
      name: nginx-proxy

#CONTAINERS VOLUMES
volumes:
  back-easyrgpd-postgres-data:
  back-easyrgpd-php-data:
            
